### ISSUE TITLE
Add content to the teams page

### ISSUE THREAD

**Issue by Abiola-Farounbi** [CoffeeWithDevs/CodeWithUs#13]
The teams page is currently empty

**Comment by kittu2karthik** [comment]
hey @Abiola-Farounbi  
can you please assign this issue to me

**Comment by kundanb** [comment]
Hey @Abiola-Farounbi , add hacktober labels to your issue.

**Comment by kumarmanish03** [comment]
@kittu2karthik go ahead!

**Comment by kumarmanish03** [comment]
@kittu2karthik any updates?
