### ISSUE TITLE
Contact Section going out of block!

### ISSUE THREAD

**Issue by kundanb** [CoffeeWithDevs/CodeWithUs#14]
Please fix form elements so that they can attain a suitable width according to the viewport, and make them responsive as well.

![image](https://user-images.githubusercontent.com/67975986/97134638-ed9b7c00-1773-11eb-98a2-b5d0f704fc04.png)

**Comment by superneutrino8** [comment]
Hey @kundanb, Can I work on this?

**Comment by kittu2karthik** [comment]
hey @kundanb  this issue look perfect for me can you assign it to me

**Comment by kundanb** [comment]
sry @kittu2karthik , @superneutrino8 resolved the issue!
