### ISSUE TITLE
Make Navbar Responsive

### ISSUE THREAD

**Issue by kumarmanish03** [CoffeeWithDevs/CodeWithUs#18]
As seen the navbar is not responsive for small screens

Your task is to make the navbar responsive for mobile devices as well
You may try for Hamburger navbar

PS: Provide a live link/screenshot, as it is very convenient to us for review

![Screenshot from 2020-10-26 23-15-57](https://user-images.githubusercontent.com/41566808/97208757-7e5c7100-17e1-11eb-9103-64d98dd98d01.png)

**Comment by verma-shivani** [comment]
may i resolve this

**Comment by kumarmanish03** [comment]
@verma-shivani go ahead!!!
also, add your details to the contribution folder, for more see #2 
One more thing, you have to get it done as soon as possible unless we may assign it to another one

**Comment by verma-shivani** [comment]
okay,Thank You!

**Comment by kumarmanish03** [comment]
This issue is open for claims

**Comment by ka-hn** [comment]
@kumarmanish03  Can I take this issue?

**Comment by kumarmanish03** [comment]
@ka-hn go ahead!!!
Also, you have to get it done as soon as possible unless we may assign it to another one

**Comment by iamrishavraj1** [comment]
Hey,If This Issue Still Open then Please Assign me for this.

**Comment by ka-hn** [comment]
@iamrishavraj1 I will soon make a PR on this

**Comment by ka-hn** [comment]
@kumarmanish03 Have a look on my suggestion and see what you think #25
