### ISSUE TITLE
Add a preloader to the website

### ISSUE THREAD

**Issue by kumarmanish03** [CoffeeWithDevs/CodeWithUs#32]
Your task is to add a preloader to the website. You may motivate by this example: http://geekhaven.github.io/Geektoberfest-Main/
Preloader maybe gif, png, but make sure it is transparent
NOTE: Choose any preloader but make sure it is cool :smile:

**Comment by IC1101Virgo** [comment]
Can I work on this?

**Comment by kumarmanish03** [comment]
@IC1101Virgo go ahead!
Also, add yourself in contributors, read #2

**Comment by kumarmanish03** [comment]
Hey, @IC1101Virgo the loader you added was not working fine so I reverted the merge PR
Please create a new PR having a proper loader
Also, provide the live link this time
