### ISSUE TITLE
Add a 'Scroll to top button"

### ISSUE THREAD

**Issue by kumarmanish03** [CoffeeWithDevs/CodeWithUs#33]
You have to add a scroll to top button, It should be on the bottom right of the site.
Make sure the button should only visible when I am scrolled down, not when I am already at the top. Also, you'll have to use javascript or something so that when I click the button, it actually visibly scrolls to the top, instead of just snapping to the top.

**Comment by nusart** [comment]
Hi @kumarmanish03 I think I have the snippet for this. Please assign me this issue.

**Comment by kumarmanish03** [comment]
@Nusart go for it!!!

**Comment by kumarmanish03** [comment]
@Nusart you have to add yourself in contributions folder first, read issue #2

**Comment by nusart** [comment]
@kumarmanish03 Do I need to create a PR for making changes to contributions folder?

**Comment by kumarmanish03** [comment]
@Nusart Yes

**Comment by nusart** [comment]
@kumarmanish03 Created a PR#43 to add a scroll up button. Please let me know if any edits are needed.
