### ISSUE TITLE
Create a GET STARTED Button

### ISSUE THREAD

**Issue by kumarmanish03** [CoffeeWithDevs/CodeWithUs#34]
Your task is to create a "GET STARTED" button in the showcase which will redirect to the main repo (https://github.com/CoffeeWithDevs/CodeWithUs/)
Also, the link must be opened in a new tab

**Comment by kumarmanish03** [comment]
@kittu2karthik you have been assigned to this issue, go ahead!!!

**Comment by pratyushakatti13** [comment]
Hey, can I pick this issue?

**Comment by kumarmanish03** [comment]
Yes @pratyushakatti13 , go ahead!
But first add yourself in contributors , read #2

**Comment by pratyushakatti13** [comment]
I have pulled a request. Please review it. Thank you!
