### ISSUE TITLE
Add a custom scroll bar

### ISSUE THREAD

**Issue by kumarmanish03** [CoffeeWithDevs/CodeWithUs#36]
The default scrollbar is getting in the way of the overall theme. They need to be customized.
Your task to create a custom scrollbar for the site

**Comment by Yash7818** [comment]
hello, @kumarmanish03 
may i work on this

**Comment by kumarmanish03** [comment]
@Yash7818 go ahead!
Also read #2 and create PR for same

**Comment by Yash7818** [comment]
@kumarmanish03 
what if i remove scrollbar,actually theme is looking great without it.

**Comment by kumarmanish03** [comment]
No, You have to add a custom scrollbar

**Comment by Yash7818** [comment]
a custom scrollbar is added please tell if it need changes
