### ISSUE TITLE
Redesign the profile page

### ISSUE THREAD

**Issue by kumarmanish03** [CoffeeWithDevs/CodeWithUs#37]
Your task is to redesign the profile page
Note: profile page asks for username parameter, you may go to the profile page of a user on clicking profile button in the participants' section

Design a landscape profile of height 100vh, user image should be on the left side and its details on the right side

Currently, the profile page looks like:
![Screenshot from 2020-10-28 13-51-54](https://user-images.githubusercontent.com/41566808/97410368-fc756080-1924-11eb-9742-93f68d2c0355.png)

**Comment by kumarmanish03** [comment]
Hello team members @superneutrino8 @baidaadarsh @ritviksharma3 @Matrix278 @kittu2karthik @ka-hn @casiimir @eficoresources @nitish-awasthi @iamrishavraj1 @snehaa1989
There are some new issues, do get assigned to yourself before others :smile: :boom: :money_mouth_face:

**Comment by iamrishavraj1** [comment]
Hey Please assign me For this issue

**Comment by kumarmanish03** [comment]
@iamrishavraj1 go ahead!!!

**Comment by kittu2karthik** [comment]
Hey @kumarmanish03 
Can you assign me this issue please

**Comment by kumarmanish03** [comment]
@kittu2karthik this issue is assigned to @iamrishavraj1 if you want I assign you another issue

**Comment by superneutrino8** [comment]
@kumarmanish03 @iamrishavraj1, Let me know if any help required with the design.

**Comment by kumarmanish03** [comment]
@superneutrino8 Sure Vivek!!!

**Comment by nusart** [comment]
Hi, is this issue still available? Can I work on this?

**Comment by kumarmanish03** [comment]
Hey @Nusart this issue currently assigned to @iamrishavraj1 you can take other issues

**Comment by iamrishavraj1** [comment]
> @kumarmanish03 @iamrishavraj1, Let me know if any help required with the design.

Sure 😃

**Comment by iamrishavraj1** [comment]
@kumarmanish03 Please Review My PR.

**Comment by kumarmanish03** [comment]
Hey, @superneutrino8 if you want you to go for this issue I assign it to you, as @iamrishavraj1 facing some problems but make sure you should not change existing classes, elements. Add new classes instead.
Be careful about the parameter, add ```?username=susuperneutrino8``` after URL
One can see his profile at https://coffeewithdevs.github.io/CodeWithUs/profile.html?username=superneutrino8

**Comment by superneutrino8** [comment]
@kumarmanish03 Sure!
