### ISSUE TITLE
Make site Mobile Responsive

### ISSUE THREAD

**Issue by kumarmanish03** [CoffeeWithDevs/CodeWithUs#48]
Currently, the site is not mobile responsive. Your task to make the site responsive for mobile devices as well

**Comment by slytherin20** [comment]
Hi @kumarmanish03,
Can I work on this?

**Comment by kumarmanish03** [comment]
@slytherin20 go ahead!
But first, add yourself in contributors first, read #2 and create PR for same

**Comment by Yash7818** [comment]
Hello, @kumarmanish03 
May I work on this?

**Comment by kumarmanish03** [comment]
@Yash7818 this issue is already assigned, you may another issue

**Comment by kumarmanish03** [comment]
Also read #2 and create PR for same
