### ISSUE TITLE
Add a Responsive Footer To The Home Page

### ISSUE THREAD

**Issue by geeks5551** [CoffeeWithDevs/CodeWithUs#6]
Presently There Is dull Footer In the Home Page, Add A Custom Styled Footer to the Home Page  
Add A Live Link/ Screenshots For better reviewing

**Comment by UshasriMavuri1999** [comment]
Hey @geeks5551, i would like to work on this...
Can you please assign this to me!

**Comment by iamrishavraj1** [comment]
Hey,Please Assign me This Issue

**Comment by geeks5551** [comment]
@UshasriMavuri1999 go ahead!!

**Comment by geeks5551** [comment]
@iamrishavraj1 I have assigned you already one issue, let others also have a chance

**Comment by ritviksharma3** [comment]
@geeks5551 Hey ! Is this still issue open ? If yes, please assign me will get it done ASAP.

**Comment by kumarmanish03** [comment]
@ritviksharma3 please read #2 this issue first

**Comment by kumarmanish03** [comment]
Hey @UshasriMavuri1999 do have a look  in this #2 also

**Comment by ritviksharma3** [comment]
@kumarmanish03 Ok, So Do I have to add that before creating the PR ? Or I can push it together ?

**Comment by kumarmanish03** [comment]
@ritviksharma3 you may push it together. But do mention the issue no. you solving in your PR
ex. you have to comment in your pr as #2 if you solved 2nd issue
If you find any difficulty do let me know

**Comment by ritviksharma3** [comment]
Hi ! @kumarmanish03 @geeks5551 Please review PR #17 created for issue #6. Thank you & Happy Developing
