### ISSUE TITLE
Design A Favicon For The Title

### ISSUE THREAD

**Issue by geeks5551** [CoffeeWithDevs/CodeWithUs#7]
Presently there is no favicon to the website, add a designed favicon to the website
also, add a live link/screenshot for better reviewing

**Comment by baidaadarsh** [comment]
Hi,

@geeks5551  Added a PR for the same, please check

**Comment by geeks5551** [comment]
@baidaadarsh  go ahead!!

**Comment by baidaadarsh** [comment]
Hey, @geeks5551 have already commited the necessary files for the favicon, just an approval is required.
